version: '3'

services:
  mstts:
    container_name: ms-tts
    image: ljmalyp/ms-tts:latest
    ports:
      - 3000:3000
    environment:
      - TOKEN=3cedbb0b635c4e758780b78a0c66a379

  bitwarden:
    image: vaultwarden/server:latest
    container_name: bitwarden
    ports:
      - 80:80
    environment:
      - SERVER_ADMIN_EMAIL=yxx95lz@163.com
      - SIGNUPS_ALLOWED=false
      - INVITATIONS_ALLOWED=true
      - WEBSOCKET_ENABLED=true
      - DATABASE_URL=/data/bitwarden.db
      - ROCKET_WORKERS=10
      - WEB_VAULT_ENABLED=true
      - ADMIN_TOKEN=yaoqing12345678
    volumes:
      - bitwardendata:/data

volumes:
  bitwardendata:
